import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { cn } from "@/lib/utils";

import Providers from "@/components/providers";

import AppHeader from "@/components/app-header";
import AppSidebar from "@/components/ui/sidebar/app-sidebar";
import { SidebarInset } from "@/components/ui/sidebar";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn("antialiased", geistSans.variable, geistMono.variable)}
      >
        <Providers>
          <AppSidebar />

          <SidebarInset>
            <main>
              <AppHeader />
              {children}
            </main>
          </SidebarInset>
        </Providers>
      </body>
    </html>
  );
}
